name: Tests

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]
  
permissions: 
  contents: read

jobs: 
  test:
    name: Rust on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        - os: ubuntu-latest
          target: x86_64-unknown-linux-gnu
          toolchain: stable
        - os: macos-latest
          target: x86_64-apple-darwin
          toolchain: stable
          # TODO: also aarch64 / M1
        - os: windows-latest
          target: x86_64-pc-windows-gnu
          toolchain: stable
    steps:
      - uses: dtolnay/rust-toolchain@master
      - name: Install toolchain
        with: 
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
      - run: ${{ matrix.deps }}
      
      - name: Run Tests
        run: cargo test --target ${{ matrix.target }}
